version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 12
    commands:
       - npm install
       - npm install -g serverless
       
  
  build:
    commands:
       - aws cloudformation package --template-file serverless.yml --s3-bucket sls-dev-serverlessdeploymentbucket-385sagfyfitn --output-template-file compiled-cloudformation-template.json
       